# Generated by Django 6.0.3 on 2026-03-10 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('NEED', 'Need'), ('IN_PROGRESS', 'In progress'), ('DELIVERED', 'Delivered')], max_length=20)),
                ('new_status', models.CharField(choices=[('NEED', 'Need'), ('IN_PROGRESS', 'In progress'), ('DELIVERED', 'Delivered')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
