# Generated by Django 6.0.3 on 2026-03-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cluster_order_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='route_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
